
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace FloppyMaintenance
{
	/// <summary>
	/// Summary description for frmAboutbox.
	/// </summary>
	public partial class frmAboutbox : System.Windows.Forms.Form
	{

		public frmAboutbox()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
		}
	}
}
