//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace FloppyMaintenance
{
    /// <summary>
    /// Summary description for frmAboutbox.
    /// </summary>

    partial class frmAboutbox : System.Windows.Forms.Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.PictureBox picStatic1;
        private System.Windows.Forms.Label lblStatic2;
        private System.Windows.Forms.Label lblStatic3;
        private System.Windows.Forms.Button btnIdok;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.Label lblStatic5;
        private System.Windows.Forms.Label lblStatic6;
        private System.Windows.Forms.Label lblStatic7;
        private System.Windows.Forms.Label lblStatic8;
        private System.Windows.Forms.Label lblStatic9;
        private System.Windows.Forms.Label lblStatic10;
        private System.Windows.Forms.Label lblStatic11;
        private System.Windows.Forms.Label lblStatic12;





        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region DudeLabs LLC RCConverter generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmAboutbox));
            this.picStatic1 = new System.Windows.Forms.PictureBox();
            this.lblStatic2 = new System.Windows.Forms.Label();
            this.lblStatic3 = new System.Windows.Forms.Label();
            this.btnIdok = new System.Windows.Forms.Button();
            this.lblStatic4 = new System.Windows.Forms.Label();
            this.lblStatic5 = new System.Windows.Forms.Label();
            this.lblStatic6 = new System.Windows.Forms.Label();
            this.lblStatic7 = new System.Windows.Forms.Label();
            this.lblStatic8 = new System.Windows.Forms.Label();
            this.lblStatic9 = new System.Windows.Forms.Label();
            this.lblStatic10 = new System.Windows.Forms.Label();
            this.lblStatic11 = new System.Windows.Forms.Label();
            this.lblStatic12 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.picStatic1)).BeginInit();
            this.SuspendLayout();
            // 
            // picStatic1
            // 
            this.picStatic1.Image = ((System.Drawing.Image)(resources.GetObject("picStatic1.Image")));
            this.picStatic1.Location = new System.Drawing.Point(10, 11);
            this.picStatic1.Name = "picStatic1";
            this.picStatic1.Size = new System.Drawing.Size(30, 34);
            this.picStatic1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.picStatic1.TabIndex = 1;
            this.picStatic1.TabStop = false;
            // 
            // lblStatic2
            // 
            this.lblStatic2.AutoSize = true;
            this.lblStatic2.Location = new System.Drawing.Point(50, 11);
            this.lblStatic2.Name = "lblStatic2";
            this.lblStatic2.Size = new System.Drawing.Size(165, 13);
            this.lblStatic2.TabIndex = 2;
            this.lblStatic2.Text = "FloppyMaintenance Version 3.0.1";
            // 
            // lblStatic3
            // 
            this.lblStatic3.AutoSize = true;
            this.lblStatic3.Location = new System.Drawing.Point(50, 30);
            this.lblStatic3.Name = "lblStatic3";
            this.lblStatic3.Size = new System.Drawing.Size(262, 13);
            this.lblStatic3.TabIndex = 3;
            this.lblStatic3.Text = "Copyright (C) 2000-2019 Evenson Consulting Services";
            // 
            // btnIdok
            // 
            this.btnIdok.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnIdok.Location = new System.Drawing.Point(393, 11);
            this.btnIdok.Name = "btnIdok";
            this.btnIdok.Size = new System.Drawing.Size(75, 24);
            this.btnIdok.TabIndex = 4;
            this.btnIdok.Text = "OK";
            // 
            // lblStatic4
            // 
            this.lblStatic4.Location = new System.Drawing.Point(33, 168);
            this.lblStatic4.Name = "lblStatic4";
            this.lblStatic4.Size = new System.Drawing.Size(400, 32);
            this.lblStatic4.TabIndex = 5;
            this.lblStatic4.Text = "This is a maintenance utility for managing floppy diskette images (.dsk files). N" +
    "o warranties are given either implied or explicit, so use this program at your o" +
    "wn risk. ";
            // 
            // lblStatic5
            // 
            this.lblStatic5.AutoSize = true;
            this.lblStatic5.Location = new System.Drawing.Point(15, 58);
            this.lblStatic5.Name = "lblStatic5";
            this.lblStatic5.Size = new System.Drawing.Size(92, 13);
            this.lblStatic5.TabIndex = 6;
            this.lblStatic5.Text = "Special thanks to:";
            // 
            // lblStatic6
            // 
            this.lblStatic6.AutoSize = true;
            this.lblStatic6.Location = new System.Drawing.Point(33, 77);
            this.lblStatic6.Name = "lblStatic6";
            this.lblStatic6.Size = new System.Drawing.Size(430, 13);
            this.lblStatic6.TabIndex = 7;
            this.lblStatic6.Text = "Ian Blythe for the icon, the original suggestion and the added suggestions for im" +
    "provement";
            // 
            // lblStatic7
            // 
            this.lblStatic7.AutoSize = true;
            this.lblStatic7.Location = new System.Drawing.Point(33, 99);
            this.lblStatic7.Name = "lblStatic7";
            this.lblStatic7.Size = new System.Drawing.Size(286, 13);
            this.lblStatic7.TabIndex = 8;
            this.lblStatic7.Text = "�yvind Hagestuen for reminding me to finish this application";
            // 
            // lblStatic8
            // 
            this.lblStatic8.AutoSize = true;
            this.lblStatic8.Location = new System.Drawing.Point(78, 280);
            this.lblStatic8.Name = "lblStatic8";
            this.lblStatic8.Size = new System.Drawing.Size(156, 13);
            this.lblStatic8.TabIndex = 9;
            this.lblStatic8.Text = "SWTPC 6800/6809 emulation: ";
            // 
            // lblStatic9
            // 
            this.lblStatic9.Location = new System.Drawing.Point(33, 230);
            this.lblStatic9.Name = "lblStatic9";
            this.lblStatic9.Size = new System.Drawing.Size(400, 29);
            this.lblStatic9.TabIndex = 10;
            this.lblStatic9.Text = "If you have any questions or suggestions for improvement please email them to mev" +
    "enson@ga.prestige.net";
            // 
            // lblStatic10
            // 
            this.lblStatic10.AutoSize = true;
            this.lblStatic10.Location = new System.Drawing.Point(33, 208);
            this.lblStatic10.Name = "lblStatic10";
            this.lblStatic10.Size = new System.Drawing.Size(404, 13);
            this.lblStatic10.TabIndex = 11;
            this.lblStatic10.Text = "All efforts have been made to insure that this program performs its intended purp" +
    "ose. ";
            // 
            // lblStatic11
            // 
            this.lblStatic11.AutoSize = true;
            this.lblStatic11.Location = new System.Drawing.Point(234, 280);
            this.lblStatic11.Name = "lblStatic11";
            this.lblStatic11.Size = new System.Drawing.Size(149, 13);
            this.lblStatic11.TabIndex = 12;
            this.lblStatic11.Text = "www.evenson-consulting.com";
            // 
            // lblStatic12
            // 
            this.lblStatic12.Location = new System.Drawing.Point(33, 122);
            this.lblStatic12.Name = "lblStatic12";
            this.lblStatic12.Size = new System.Drawing.Size(426, 34);
            this.lblStatic12.TabIndex = 13;
            this.lblStatic12.Text = "Donald Coates for identifiying the missing cylinder bug and the file exists impor" +
    "t bug as well as the recently  discovered create bug which has been fixed in ver" +
    "sion 2.0.0";
            // 
            // frmAboutbox
            // 
            this.AcceptButton = this.btnIdok;
            this.ClientSize = new System.Drawing.Size(486, 325);
            this.Controls.Add(this.btnIdok);
            this.Controls.Add(this.lblStatic10);
            this.Controls.Add(this.lblStatic11);
            this.Controls.Add(this.lblStatic12);
            this.Controls.Add(this.lblStatic2);
            this.Controls.Add(this.lblStatic3);
            this.Controls.Add(this.lblStatic4);
            this.Controls.Add(this.lblStatic5);
            this.Controls.Add(this.lblStatic6);
            this.Controls.Add(this.lblStatic7);
            this.Controls.Add(this.lblStatic8);
            this.Controls.Add(this.lblStatic9);
            this.Controls.Add(this.picStatic1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmAboutbox";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "About FloppyMaintenance";
            ((System.ComponentModel.ISupportInitialize)(this.picStatic1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion

    }
}
