
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace FloppyMaintenance
{
	/// <summary>
	/// Summary description for frmDialogOptions.
	/// </summary>
	public partial class frmDialogOptions : System.Windows.Forms.Form
	{
        public bool m_nExpandTabs;
        public bool m_nAddLinefeed;
        public bool m_nCompactBinary;
        public bool m_nStripLinefeed;
        public bool m_nCompressSpaces;
        public bool m_nConvertLfOnly;
        public bool m_nConvertLfOnlyToCrLf;
        public bool m_nConvertLfOnlyToCr;
        public bool useExternalEditor;

        public string editor;

        bool logFloppyAccess = false;
        string os9FloppyWritesFile = "";

        public frmDialogOptions()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

            //
			// TODO: Add any constructor code after InitializeComponent call
			//

            m_nExpandTabs           = Program.GetConfigurationAttribute("Global/FileMaintenance/FileExport/ExpandTabs"          , "enabled", "0") == "1" ? true : false;
            m_nAddLinefeed          = Program.GetConfigurationAttribute("Global/FileMaintenance/FileExport/AddLinefeed"         , "enabled", "0") == "1" ? true : false;
            m_nCompactBinary        = Program.GetConfigurationAttribute("Global/FileMaintenance/BinaryFile/CompactBinary"       , "enabled", "0") == "1" ? true : false;
            m_nStripLinefeed        = Program.GetConfigurationAttribute("Global/FileMaintenance/FileImport/StripLinefeed"       , "enabled", "0") == "1" ? true : false;
            m_nCompressSpaces       = Program.GetConfigurationAttribute("Global/FileMaintenance/FileImport/CompressSpaces"      , "enabled", "0") == "1" ? true : false;

            m_nConvertLfOnly        = Program.GetConfigurationAttribute("Global/FileMaintenance/FileImport/ConvertLfOnly"       , "enabled", "0") == "1" ? true : false;
            if (m_nConvertLfOnly)
            {
                m_nConvertLfOnlyToCrLf  = Program.GetConfigurationAttribute("Global/FileMaintenance/FileImport/ConvertLfOnlyToCrLf" , "enabled", "0") == "1" ? true : false;
                m_nConvertLfOnlyToCr    = Program.GetConfigurationAttribute("Global/FileMaintenance/FileImport/ConvertLfOnlyToCr"   , "enabled", "0") == "1" ? true : false;
            }
            else
            {
                m_nConvertLfOnlyToCrLf  = false;
                m_nConvertLfOnlyToCr    = false;
            }

            checkBoxLogOS9FileWrites.Checked = Program.GetConfigurationAttribute("Global/FileMaintenance", "LogOS9FloppyWrites", "N") == "Y" ? true : false;
            textBoxLogOS9FileWriteLocation.Text = Program.GetConfigurationAttribute("Global/FileMaintenance", "os9FloppyWritesFile", "");

            //editor              = Program.GetConfigurationAttribute("Global/FileMaintenance", "EditorPath", "");
            //useExternalEditor   = Program.GetConfigurationAttribute("Global/FileMaintenance", "UseExternalEditor", "N") == "Y" ? true : false;
        }

        private void ButtonOK_Click(object sender, EventArgs e)
        {
            m_nAddLinefeed        = chkCheckAddLf.Checked;
            m_nCompactBinary      = chkCheckCompactBin.Checked;
            m_nCompressSpaces     = chkCheckCompressSpaces.Checked;
            m_nConvertLfOnlyToCrLf= chkCheckConvertLfOnlyToCrlf.Checked;
            m_nConvertLfOnlyToCr  = chkCheckConvertLfOnlyToCrOnly.Checked;
            m_nExpandTabs         = chkCheckExpandTabs.Checked;
            m_nStripLinefeed      = chkCheckStripLf.Checked;
            m_nConvertLfOnly      = m_nConvertLfOnlyToCrLf || m_nConvertLfOnlyToCr;

            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileExport/ExpandTabs"           , "enabled", m_nExpandTabs          ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileExport/AddLinefeed"          , "enabled", m_nAddLinefeed         ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/BinaryFile/CompactBinary"        , "enabled", m_nCompactBinary       ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileImport/StripLinefeed"        , "enabled", m_nStripLinefeed       ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileImport/CompressSpaces"       , "enabled", m_nCompressSpaces      ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileImport/ConvertLfOnly"        , "enabled", m_nConvertLfOnly       ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileImport/ConvertLfOnlyToCrLf"  , "enabled", m_nConvertLfOnlyToCrLf ? "1" : "0");
            Program.SaveConfigurationAttribute("Global/FileMaintenance/FileImport/ConvertLfOnlyToCr"    , "enabled", m_nConvertLfOnlyToCr   ? "1" : "0");

            Program.SaveConfigurationAttribute("Global/FileMaintenance", "LogOS9FloppyWrites", checkBoxLogOS9FileWrites.Checked ? "Y" : "N");
            Program.SaveConfigurationAttribute("Global/FileMaintenance", "os9FloppyWritesFile", textBoxLogOS9FileWriteLocation.Text);
        }

        private void ButtonCancel_Click(object sender, EventArgs e)
        {

        }

        private void FrmDialogOptions_Load(object sender, EventArgs e)
        {
            chkCheckAddLf.Checked                   = m_nAddLinefeed;
            chkCheckCompactBin.Checked              = m_nCompactBinary;
            chkCheckCompressSpaces.Checked          = m_nCompressSpaces;
            chkCheckConvertLfOnlyToCrlf.Checked     = m_nConvertLfOnlyToCrLf;
            chkCheckConvertLfOnlyToCrOnly.Checked   = m_nConvertLfOnlyToCr;
            chkCheckExpandTabs.Checked              = m_nExpandTabs;
            chkCheckStripLf.Checked                 = m_nStripLinefeed;
        }
    }
}
