//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace FloppyMaintenance
{
    /// <summary>
    /// Summary description for frmDialogValidFilename.
    /// </summary>

    partial class frmDialogValidFilename : System.Windows.Forms.Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.TextBox txtEditValidFilename;
        private System.Windows.Forms.Button btnIdok;
        private System.Windows.Forms.Button btnIdcancel;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.Label lblStatic2;





        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region DudeLabs LLC RCConverter generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.txtEditValidFilename = new System.Windows.Forms.TextBox();
            this.btnIdok = new System.Windows.Forms.Button();
            this.btnIdcancel = new System.Windows.Forms.Button();
            this.lblStatic1 = new System.Windows.Forms.Label();
            this.lblStatic2 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // txtEditValidFilename
            // 
            this.txtEditValidFilename.Location = new System.Drawing.Point(170, 77);
            this.txtEditValidFilename.Name = "txtEditValidFilename";
            this.txtEditValidFilename.ScrollBars = System.Windows.Forms.ScrollBars.Horizontal;
            this.txtEditValidFilename.Size = new System.Drawing.Size(99, 20);
            this.txtEditValidFilename.TabIndex = 1;
            // 
            // btnIdok
            // 
            this.btnIdok.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnIdok.Location = new System.Drawing.Point(194, 11);
            this.btnIdok.Name = "btnIdok";
            this.btnIdok.Size = new System.Drawing.Size(75, 24);
            this.btnIdok.TabIndex = 2;
            this.btnIdok.Text = "OK";
            // 
            // btnIdcancel
            // 
            this.btnIdcancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnIdcancel.Location = new System.Drawing.Point(194, 38);
            this.btnIdcancel.Name = "btnIdcancel";
            this.btnIdcancel.Size = new System.Drawing.Size(75, 24);
            this.btnIdcancel.TabIndex = 3;
            this.btnIdcancel.Text = "Cancel";
            // 
            // lblStatic1
            // 
            this.lblStatic1.Location = new System.Drawing.Point(20, 21);
            this.lblStatic1.Name = "lblStatic1";
            this.lblStatic1.Size = new System.Drawing.Size(146, 57);
            this.lblStatic1.TabIndex = 4;
            this.lblStatic1.Text = "Source filename format is not supported by FLEX 2.0. The target filename can only" +
    " be in 8.3 format.";
            // 
            // lblStatic2
            // 
            this.lblStatic2.AutoSize = true;
            this.lblStatic2.Location = new System.Drawing.Point(10, 82);
            this.lblStatic2.Name = "lblStatic2";
            this.lblStatic2.Size = new System.Drawing.Size(157, 13);
            this.lblStatic2.TabIndex = 5;
            this.lblStatic2.Text = "Please enter a valid 8.3 filespec";
            // 
            // frmDialogValidFilename
            // 
            this.AcceptButton = this.btnIdok;
            this.ClientSize = new System.Drawing.Size(287, 106);
            this.Controls.Add(this.btnIdcancel);
            this.Controls.Add(this.btnIdok);
            this.Controls.Add(this.lblStatic1);
            this.Controls.Add(this.lblStatic2);
            this.Controls.Add(this.txtEditValidFilename);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmDialogValidFilename";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Get a Valid 8.3 Filespec";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FrmDialogValidFilename_FormClosing);
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion

    }
}
