
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace FloppyMaintenance
{
	/// <summary>
	/// Summary description for frmDialogValidFilename.
	/// </summary>
	public partial class frmDialogValidFilename : System.Windows.Forms.Form
	{
        public string m_EditValidFilename = "";

        public frmDialogValidFilename()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
		}

        private void FrmDialogValidFilename_FormClosing(object sender, FormClosingEventArgs e)
        {
            m_EditValidFilename = txtEditValidFilename.Text;
        }
    }
}
