//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace FloppyMaintenance
{
    /// <summary>
    /// Summary description for frmDialogOptions.
    /// </summary>

    partial class frmDialogOptions : System.Windows.Forms.Form
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;
        private System.Windows.Forms.GroupBox grpStatic1;
        private System.Windows.Forms.GroupBox grpStatic2;
        private System.Windows.Forms.CheckBox chkCheckAddLf;
        private System.Windows.Forms.CheckBox chkCheckExpandTabs;
        private System.Windows.Forms.CheckBox chkCheckCompactBin;
        private System.Windows.Forms.Button btnIdok;
        private System.Windows.Forms.Button btnIdcancel;
        private System.Windows.Forms.GroupBox grpStatic3;
        private System.Windows.Forms.GroupBox grpStatic4;
        private System.Windows.Forms.CheckBox chkCheckStripLf;
        private System.Windows.Forms.CheckBox chkCheckCompressSpaces;
        private System.Windows.Forms.GroupBox grpStatic5;
        private System.Windows.Forms.CheckBox chkCheckConvertLfOnlyToCrOnly;
        private System.Windows.Forms.CheckBox chkCheckConvertLfOnlyToCrlf;





        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region DudeLabs LLC RCConverter generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.grpStatic1 = new System.Windows.Forms.GroupBox();
            this.grpStatic2 = new System.Windows.Forms.GroupBox();
            this.chkCheckAddLf = new System.Windows.Forms.CheckBox();
            this.chkCheckExpandTabs = new System.Windows.Forms.CheckBox();
            this.grpStatic4 = new System.Windows.Forms.GroupBox();
            this.chkCheckCompressSpaces = new System.Windows.Forms.CheckBox();
            this.chkCheckConvertLfOnlyToCrlf = new System.Windows.Forms.CheckBox();
            this.chkCheckConvertLfOnlyToCrOnly = new System.Windows.Forms.CheckBox();
            this.chkCheckStripLf = new System.Windows.Forms.CheckBox();
            this.chkCheckCompactBin = new System.Windows.Forms.CheckBox();
            this.btnIdok = new System.Windows.Forms.Button();
            this.btnIdcancel = new System.Windows.Forms.Button();
            this.grpStatic3 = new System.Windows.Forms.GroupBox();
            this.grpStatic5 = new System.Windows.Forms.GroupBox();
            this.buttonOK = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.checkBoxLogOS9FileWrites = new System.Windows.Forms.CheckBox();
            this.textBoxLogOS9FileWriteLocation = new System.Windows.Forms.TextBox();
            this.grpStatic1.SuspendLayout();
            this.grpStatic2.SuspendLayout();
            this.grpStatic4.SuspendLayout();
            this.grpStatic3.SuspendLayout();
            this.grpStatic5.SuspendLayout();
            this.SuspendLayout();
            // 
            // grpStatic1
            // 
            this.grpStatic1.Controls.Add(this.grpStatic2);
            this.grpStatic1.Controls.Add(this.grpStatic4);
            this.grpStatic1.Location = new System.Drawing.Point(16, 16);
            this.grpStatic1.Name = "grpStatic1";
            this.grpStatic1.Size = new System.Drawing.Size(474, 177);
            this.grpStatic1.TabIndex = 1;
            this.grpStatic1.TabStop = false;
            this.grpStatic1.Text = "Text File Processing Options";
            // 
            // grpStatic2
            // 
            this.grpStatic2.Controls.Add(this.chkCheckAddLf);
            this.grpStatic2.Controls.Add(this.chkCheckExpandTabs);
            this.grpStatic2.Location = new System.Drawing.Point(14, 27);
            this.grpStatic2.Name = "grpStatic2";
            this.grpStatic2.Size = new System.Drawing.Size(210, 130);
            this.grpStatic2.TabIndex = 2;
            this.grpStatic2.TabStop = false;
            this.grpStatic2.Text = "Export Options";
            // 
            // chkCheckAddLf
            // 
            this.chkCheckAddLf.Location = new System.Drawing.Point(24, 26);
            this.chkCheckAddLf.Name = "chkCheckAddLf";
            this.chkCheckAddLf.Size = new System.Drawing.Size(164, 17);
            this.chkCheckAddLf.TabIndex = 3;
            this.chkCheckAddLf.Text = "Add Linefeeds during Export";
            // 
            // chkCheckExpandTabs
            // 
            this.chkCheckExpandTabs.Location = new System.Drawing.Point(24, 47);
            this.chkCheckExpandTabs.Name = "chkCheckExpandTabs";
            this.chkCheckExpandTabs.Size = new System.Drawing.Size(158, 17);
            this.chkCheckExpandTabs.TabIndex = 4;
            this.chkCheckExpandTabs.Text = "Expand Tabs during Export";
            // 
            // grpStatic4
            // 
            this.grpStatic4.Controls.Add(this.chkCheckCompressSpaces);
            this.grpStatic4.Controls.Add(this.chkCheckConvertLfOnlyToCrlf);
            this.grpStatic4.Controls.Add(this.chkCheckConvertLfOnlyToCrOnly);
            this.grpStatic4.Controls.Add(this.chkCheckStripLf);
            this.grpStatic4.Location = new System.Drawing.Point(241, 27);
            this.grpStatic4.Name = "grpStatic4";
            this.grpStatic4.Size = new System.Drawing.Size(210, 130);
            this.grpStatic4.TabIndex = 9;
            this.grpStatic4.TabStop = false;
            this.grpStatic4.Text = "Import Options";
            // 
            // chkCheckCompressSpaces
            // 
            this.chkCheckCompressSpaces.Location = new System.Drawing.Point(21, 47);
            this.chkCheckCompressSpaces.Name = "chkCheckCompressSpaces";
            this.chkCheckCompressSpaces.Size = new System.Drawing.Size(178, 17);
            this.chkCheckCompressSpaces.TabIndex = 11;
            this.chkCheckCompressSpaces.Text = "Compress Spaces during Import";
            // 
            // chkCheckConvertLfOnlyToCrlf
            // 
            this.chkCheckConvertLfOnlyToCrlf.Location = new System.Drawing.Point(21, 88);
            this.chkCheckConvertLfOnlyToCrlf.Name = "chkCheckConvertLfOnlyToCrlf";
            this.chkCheckConvertLfOnlyToCrlf.Size = new System.Drawing.Size(176, 17);
            this.chkCheckConvertLfOnlyToCrlf.TabIndex = 14;
            this.chkCheckConvertLfOnlyToCrlf.Text = "Convert LF Only to CR/LF";
            // 
            // chkCheckConvertLfOnlyToCrOnly
            // 
            this.chkCheckConvertLfOnlyToCrOnly.Location = new System.Drawing.Point(21, 68);
            this.chkCheckConvertLfOnlyToCrOnly.Name = "chkCheckConvertLfOnlyToCrOnly";
            this.chkCheckConvertLfOnlyToCrOnly.Size = new System.Drawing.Size(156, 17);
            this.chkCheckConvertLfOnlyToCrOnly.TabIndex = 13;
            this.chkCheckConvertLfOnlyToCrOnly.Text = "Convert LF only to CR only";
            // 
            // chkCheckStripLf
            // 
            this.chkCheckStripLf.Location = new System.Drawing.Point(21, 26);
            this.chkCheckStripLf.Name = "chkCheckStripLf";
            this.chkCheckStripLf.Size = new System.Drawing.Size(164, 17);
            this.chkCheckStripLf.TabIndex = 10;
            this.chkCheckStripLf.Text = "Strip Linefeeds during Import";
            // 
            // chkCheckCompactBin
            // 
            this.chkCheckCompactBin.Location = new System.Drawing.Point(19, 29);
            this.chkCheckCompactBin.Name = "chkCheckCompactBin";
            this.chkCheckCompactBin.Size = new System.Drawing.Size(226, 17);
            this.chkCheckCompactBin.TabIndex = 5;
            this.chkCheckCompactBin.Text = "Compact Binary Files during Import/Export";
            // 
            // btnIdok
            // 
            this.btnIdok.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.btnIdok.Location = new System.Drawing.Point(168, 291);
            this.btnIdok.Name = "btnIdok";
            this.btnIdok.Size = new System.Drawing.Size(75, 24);
            this.btnIdok.TabIndex = 6;
            this.btnIdok.Text = "OK";
            // 
            // btnIdcancel
            // 
            this.btnIdcancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnIdcancel.Location = new System.Drawing.Point(268, 291);
            this.btnIdcancel.Name = "btnIdcancel";
            this.btnIdcancel.Size = new System.Drawing.Size(75, 24);
            this.btnIdcancel.TabIndex = 7;
            this.btnIdcancel.Text = "Cancel";
            // 
            // grpStatic3
            // 
            this.grpStatic3.Controls.Add(this.textBoxLogOS9FileWriteLocation);
            this.grpStatic3.Controls.Add(this.checkBoxLogOS9FileWrites);
            this.grpStatic3.Controls.Add(this.btnIdcancel);
            this.grpStatic3.Controls.Add(this.btnIdok);
            this.grpStatic3.Controls.Add(this.grpStatic1);
            this.grpStatic3.Controls.Add(this.grpStatic5);
            this.grpStatic3.Location = new System.Drawing.Point(10, 11);
            this.grpStatic3.Name = "grpStatic3";
            this.grpStatic3.Size = new System.Drawing.Size(513, 292);
            this.grpStatic3.TabIndex = 8;
            this.grpStatic3.TabStop = false;
            // 
            // grpStatic5
            // 
            this.grpStatic5.Controls.Add(this.chkCheckCompactBin);
            this.grpStatic5.Location = new System.Drawing.Point(16, 197);
            this.grpStatic5.Name = "grpStatic5";
            this.grpStatic5.Size = new System.Drawing.Size(474, 68);
            this.grpStatic5.TabIndex = 12;
            this.grpStatic5.TabStop = false;
            this.grpStatic5.Text = "Binary File Processing Options";
            // 
            // buttonOK
            // 
            this.buttonOK.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.buttonOK.Location = new System.Drawing.Point(178, 310);
            this.buttonOK.Name = "buttonOK";
            this.buttonOK.Size = new System.Drawing.Size(75, 23);
            this.buttonOK.TabIndex = 9;
            this.buttonOK.Text = "&OK";
            this.buttonOK.UseVisualStyleBackColor = true;
            this.buttonOK.Click += new System.EventHandler(this.ButtonOK_Click);
            // 
            // buttonCancel
            // 
            this.buttonCancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.buttonCancel.Location = new System.Drawing.Point(267, 310);
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.Size = new System.Drawing.Size(75, 23);
            this.buttonCancel.TabIndex = 10;
            this.buttonCancel.Text = "&Cancel";
            this.buttonCancel.UseVisualStyleBackColor = true;
            this.buttonCancel.Click += new System.EventHandler(this.ButtonCancel_Click);
            // 
            // checkBoxLogOS9FileWrites
            // 
            this.checkBoxLogOS9FileWrites.AutoSize = true;
            this.checkBoxLogOS9FileWrites.Location = new System.Drawing.Point(16, 269);
            this.checkBoxLogOS9FileWrites.Name = "checkBoxLogOS9FileWrites";
            this.checkBoxLogOS9FileWrites.Size = new System.Drawing.Size(114, 17);
            this.checkBoxLogOS9FileWrites.TabIndex = 13;
            this.checkBoxLogOS9FileWrites.Text = "Log OS9 file writes";
            this.checkBoxLogOS9FileWrites.UseVisualStyleBackColor = true;
            // 
            // textBoxLogOS9FileWriteLocation
            // 
            this.textBoxLogOS9FileWriteLocation.Location = new System.Drawing.Point(150, 268);
            this.textBoxLogOS9FileWriteLocation.Name = "textBoxLogOS9FileWriteLocation";
            this.textBoxLogOS9FileWriteLocation.Size = new System.Drawing.Size(340, 20);
            this.textBoxLogOS9FileWriteLocation.TabIndex = 14;
            this.textBoxLogOS9FileWriteLocation.Text = "D:\\OS9FloppyDIskWrites.txt";
            // 
            // frmDialogOptions
            // 
            this.AcceptButton = this.btnIdok;
            this.ClientSize = new System.Drawing.Size(542, 344);
            this.Controls.Add(this.buttonCancel);
            this.Controls.Add(this.buttonOK);
            this.Controls.Add(this.grpStatic3);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmDialogOptions";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Configuration Options";
            this.Load += new System.EventHandler(this.FrmDialogOptions_Load);
            this.grpStatic1.ResumeLayout(false);
            this.grpStatic2.ResumeLayout(false);
            this.grpStatic4.ResumeLayout(false);
            this.grpStatic3.ResumeLayout(false);
            this.grpStatic3.PerformLayout();
            this.grpStatic5.ResumeLayout(false);
            this.ResumeLayout(false);

        }
        #endregion

        private Button buttonOK;
        private Button buttonCancel;
        private TextBox textBoxLogOS9FileWriteLocation;
        private CheckBox checkBoxLogOS9FileWrites;
    }
}
