//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
namespace FloppyMaintenance
{
    /// <summary>
    /// Summary description for frmFloppymaintDialog.
    /// </summary>

    partial class frmFloppymaintDialog : System.Windows.Forms.Form
    {
        private System.Windows.Forms.Button btnButtonChangeDisk;
        private System.Windows.Forms.Button btnButtonCreate;
        private System.Windows.Forms.Button btnButtonEditor;
        private System.Windows.Forms.Button btnButtonOptions;
        private System.Windows.Forms.Button btnButtonImport;
        private System.Windows.Forms.Button btnButtonExport;
        private System.Windows.Forms.Button btnButtonDelete;
        private System.Windows.Forms.Button btnButtonClose;
        private System.Windows.Forms.ListView lstviewListFiles;
        private System.Windows.Forms.Label lblStaticVolumeName;
        private System.Windows.Forms.Label lblStaticCreationDate;
        private System.Windows.Forms.Label lblStaticRemainingSectors;
        private System.Windows.Forms.Label lblStatic1;
        private System.Windows.Forms.Label lblStatic2;
        private System.Windows.Forms.Label lblStatic3;
        private System.Windows.Forms.Label lblStatic4;
        private System.Windows.Forms.Label lblStaticFileCount;
        private System.Windows.Forms.GroupBox grpStatic5;
        private System.Windows.Forms.PictureBox picStaticRwStatus;
        private System.Windows.Forms.Button btnButtonRefresh;
        private System.Windows.Forms.Button btnButtonSelectAll;
        private System.Windows.Forms.Button btnButtonDeselectAll;
        private System.Windows.Forms.ListView lstviewListPartitions;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region DudeLabs LLC RCConverter generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmFloppymaintDialog));
            this.btnButtonChangeDisk = new System.Windows.Forms.Button();
            this.btnButtonCreate = new System.Windows.Forms.Button();
            this.btnButtonEditor = new System.Windows.Forms.Button();
            this.btnButtonOptions = new System.Windows.Forms.Button();
            this.btnButtonImport = new System.Windows.Forms.Button();
            this.btnButtonExport = new System.Windows.Forms.Button();
            this.btnButtonDelete = new System.Windows.Forms.Button();
            this.btnButtonClose = new System.Windows.Forms.Button();
            this.lstviewListFiles = new System.Windows.Forms.ListView();
            this.contextMenuStripListFiles = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.findToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.lblStaticVolumeName = new System.Windows.Forms.Label();
            this.lblStaticCreationDate = new System.Windows.Forms.Label();
            this.lblStaticRemainingSectors = new System.Windows.Forms.Label();
            this.lblStatic1 = new System.Windows.Forms.Label();
            this.lblStatic2 = new System.Windows.Forms.Label();
            this.lblStatic3 = new System.Windows.Forms.Label();
            this.lblStatic4 = new System.Windows.Forms.Label();
            this.lblStaticFileCount = new System.Windows.Forms.Label();
            this.grpStatic5 = new System.Windows.Forms.GroupBox();
            this.picStaticRwStatus = new System.Windows.Forms.PictureBox();
            this.btnButtonRefresh = new System.Windows.Forms.Button();
            this.btnButtonSelectAll = new System.Windows.Forms.Button();
            this.btnButtonDeselectAll = new System.Windows.Forms.Button();
            this.lstviewListPartitions = new System.Windows.Forms.ListView();
            this.treeViewFiles = new System.Windows.Forms.TreeView();
            this.menuStripMain = new System.Windows.Forms.MenuStrip();
            this.toolStripMenuItemFile = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemFileOpen = new System.Windows.Forms.ToolStripMenuItem();
            this.recentFilesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemFileNew = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripMenuItemFileClose = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator4 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripMenuItemFileRefresh = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripMenuItemFileExit = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemEdit = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemEditSelectAll = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemEditDeselectAll = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemTools = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemToolsEditor = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemToolsOptions = new System.Windows.Forms.ToolStripMenuItem();
            this.convertDSKToIMAToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemImageFile = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemImageFileImport = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemImageFileExport = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripMenuItemImageFileImportDirectory = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItemImageFileCreateDirectory = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.toolStripMenuItemImageFileDelete = new System.Windows.Forms.ToolStripMenuItem();
            this.btnButtonNewDirectory = new System.Windows.Forms.Button();
            this.labelFileFormat = new System.Windows.Forms.Label();
            this.lstViewPartitions = new System.Windows.Forms.ListView();
            this.columnHeaderPartitionName = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeaderName = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.btnButtonImportDir = new System.Windows.Forms.Button();
            this.folderBrowserDialogImportDirectory = new System.Windows.Forms.FolderBrowserDialog();
            this.btnButtonBack = new System.Windows.Forms.Button();
            this.textBoxListViewCurrentPath = new System.Windows.Forms.TextBox();
            this.toolStripSeparator6 = new System.Windows.Forms.ToolStripSeparator();
            this.verifyImageIntegrityToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.contextMenuStripListFiles.SuspendLayout();
            this.grpStatic5.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picStaticRwStatus)).BeginInit();
            this.menuStripMain.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnButtonChangeDisk
            // 
            this.btnButtonChangeDisk.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonChangeDisk.Location = new System.Drawing.Point(441, 102);
            this.btnButtonChangeDisk.Name = "btnButtonChangeDisk";
            this.btnButtonChangeDisk.Size = new System.Drawing.Size(75, 24);
            this.btnButtonChangeDisk.TabIndex = 1;
            this.btnButtonChangeDisk.Text = "&Open Disk";
            this.btnButtonChangeDisk.Click += new System.EventHandler(this.BtnButtonChangeDisk_Click);
            // 
            // btnButtonCreate
            // 
            this.btnButtonCreate.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonCreate.Location = new System.Drawing.Point(441, 129);
            this.btnButtonCreate.Name = "btnButtonCreate";
            this.btnButtonCreate.Size = new System.Drawing.Size(75, 24);
            this.btnButtonCreate.TabIndex = 2;
            this.btnButtonCreate.Text = "Cre&ate Disk";
            this.btnButtonCreate.Click += new System.EventHandler(this.BtnButtonCreate_Click);
            // 
            // btnButtonEditor
            // 
            this.btnButtonEditor.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonEditor.Location = new System.Drawing.Point(441, 279);
            this.btnButtonEditor.Name = "btnButtonEditor";
            this.btnButtonEditor.Size = new System.Drawing.Size(75, 24);
            this.btnButtonEditor.TabIndex = 3;
            this.btnButtonEditor.Text = "Edito&r";
            this.btnButtonEditor.Click += new System.EventHandler(this.BtnButtonEditor_Click);
            // 
            // btnButtonOptions
            // 
            this.btnButtonOptions.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonOptions.Location = new System.Drawing.Point(441, 305);
            this.btnButtonOptions.Name = "btnButtonOptions";
            this.btnButtonOptions.Size = new System.Drawing.Size(75, 24);
            this.btnButtonOptions.TabIndex = 4;
            this.btnButtonOptions.Text = "&Options";
            this.btnButtonOptions.Click += new System.EventHandler(this.BtnButtonOptions_Click);
            // 
            // btnButtonImport
            // 
            this.btnButtonImport.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonImport.Location = new System.Drawing.Point(441, 415);
            this.btnButtonImport.Name = "btnButtonImport";
            this.btnButtonImport.Size = new System.Drawing.Size(75, 24);
            this.btnButtonImport.TabIndex = 5;
            this.btnButtonImport.Text = "&Import";
            this.btnButtonImport.Click += new System.EventHandler(this.BtnButtonImport_Click);
            // 
            // btnButtonExport
            // 
            this.btnButtonExport.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonExport.Location = new System.Drawing.Point(441, 440);
            this.btnButtonExport.Name = "btnButtonExport";
            this.btnButtonExport.Size = new System.Drawing.Size(75, 24);
            this.btnButtonExport.TabIndex = 6;
            this.btnButtonExport.Text = "&Export";
            this.btnButtonExport.Click += new System.EventHandler(this.BtnButtonExport_Click);
            // 
            // btnButtonDelete
            // 
            this.btnButtonDelete.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonDelete.Location = new System.Drawing.Point(441, 467);
            this.btnButtonDelete.Name = "btnButtonDelete";
            this.btnButtonDelete.Size = new System.Drawing.Size(75, 24);
            this.btnButtonDelete.TabIndex = 7;
            this.btnButtonDelete.Text = "&Delete";
            this.btnButtonDelete.Click += new System.EventHandler(this.BtnButtonDelete_Click);
            // 
            // btnButtonClose
            // 
            this.btnButtonClose.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonClose.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnButtonClose.Location = new System.Drawing.Point(441, 38);
            this.btnButtonClose.Name = "btnButtonClose";
            this.btnButtonClose.Size = new System.Drawing.Size(75, 24);
            this.btnButtonClose.TabIndex = 8;
            this.btnButtonClose.Text = "&Close";
            this.btnButtonClose.Click += new System.EventHandler(this.BtnIdcancel_Click);
            // 
            // lstviewListFiles
            // 
            this.lstviewListFiles.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstviewListFiles.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lstviewListFiles.ContextMenuStrip = this.contextMenuStripListFiles;
            this.lstviewListFiles.HideSelection = false;
            this.lstviewListFiles.Location = new System.Drawing.Point(10, 102);
            this.lstviewListFiles.Name = "lstviewListFiles";
            this.lstviewListFiles.Size = new System.Drawing.Size(417, 418);
            this.lstviewListFiles.TabIndex = 9;
            this.lstviewListFiles.UseCompatibleStateImageBehavior = false;
            this.lstviewListFiles.View = System.Windows.Forms.View.Details;
            this.lstviewListFiles.DoubleClick += new System.EventHandler(this.LstviewListFiles_DoubleClick);
            // 
            // contextMenuStripListFiles
            // 
            this.contextMenuStripListFiles.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.findToolStripMenuItem});
            this.contextMenuStripListFiles.Name = "contextMenuStripListFiles";
            this.contextMenuStripListFiles.Size = new System.Drawing.Size(98, 26);
            // 
            // findToolStripMenuItem
            // 
            this.findToolStripMenuItem.Name = "findToolStripMenuItem";
            this.findToolStripMenuItem.Size = new System.Drawing.Size(97, 22);
            this.findToolStripMenuItem.Text = "&Find";
            this.findToolStripMenuItem.Click += new System.EventHandler(this.findToolStripMenuItem_Click);
            // 
            // lblStaticVolumeName
            // 
            this.lblStaticVolumeName.AutoSize = true;
            this.lblStaticVolumeName.Location = new System.Drawing.Point(104, 18);
            this.lblStaticVolumeName.Name = "lblStaticVolumeName";
            this.lblStaticVolumeName.Size = new System.Drawing.Size(0, 13);
            this.lblStaticVolumeName.TabIndex = 10;
            // 
            // lblStaticCreationDate
            // 
            this.lblStaticCreationDate.AutoSize = true;
            this.lblStaticCreationDate.Location = new System.Drawing.Point(104, 35);
            this.lblStaticCreationDate.Name = "lblStaticCreationDate";
            this.lblStaticCreationDate.Size = new System.Drawing.Size(0, 13);
            this.lblStaticCreationDate.TabIndex = 11;
            // 
            // lblStaticRemainingSectors
            // 
            this.lblStaticRemainingSectors.AutoSize = true;
            this.lblStaticRemainingSectors.Location = new System.Drawing.Point(364, 35);
            this.lblStaticRemainingSectors.Name = "lblStaticRemainingSectors";
            this.lblStaticRemainingSectors.Size = new System.Drawing.Size(0, 13);
            this.lblStaticRemainingSectors.TabIndex = 12;
            // 
            // lblStatic1
            // 
            this.lblStatic1.AutoSize = true;
            this.lblStatic1.Location = new System.Drawing.Point(10, 18);
            this.lblStatic1.Name = "lblStatic1";
            this.lblStatic1.Size = new System.Drawing.Size(71, 13);
            this.lblStatic1.TabIndex = 13;
            this.lblStatic1.Text = "Volume Label";
            // 
            // lblStatic2
            // 
            this.lblStatic2.AutoSize = true;
            this.lblStatic2.Location = new System.Drawing.Point(10, 35);
            this.lblStatic2.Name = "lblStatic2";
            this.lblStatic2.Size = new System.Drawing.Size(72, 13);
            this.lblStatic2.TabIndex = 14;
            this.lblStatic2.Text = "Creation Date";
            // 
            // lblStatic3
            // 
            this.lblStatic3.AutoSize = true;
            this.lblStatic3.Location = new System.Drawing.Point(264, 35);
            this.lblStatic3.Name = "lblStatic3";
            this.lblStatic3.Size = new System.Drawing.Size(96, 13);
            this.lblStatic3.TabIndex = 15;
            this.lblStatic3.Text = "Remaining Sectors";
            // 
            // lblStatic4
            // 
            this.lblStatic4.AutoSize = true;
            this.lblStatic4.Location = new System.Drawing.Point(264, 18);
            this.lblStatic4.Name = "lblStatic4";
            this.lblStatic4.Size = new System.Drawing.Size(54, 13);
            this.lblStatic4.TabIndex = 16;
            this.lblStatic4.Text = "File Count";
            // 
            // lblStaticFileCount
            // 
            this.lblStaticFileCount.AutoSize = true;
            this.lblStaticFileCount.Location = new System.Drawing.Point(348, 18);
            this.lblStaticFileCount.Name = "lblStaticFileCount";
            this.lblStaticFileCount.Size = new System.Drawing.Size(0, 13);
            this.lblStaticFileCount.TabIndex = 17;
            // 
            // grpStatic5
            // 
            this.grpStatic5.Controls.Add(this.lblStatic1);
            this.grpStatic5.Controls.Add(this.lblStatic2);
            this.grpStatic5.Controls.Add(this.lblStatic3);
            this.grpStatic5.Controls.Add(this.lblStatic4);
            this.grpStatic5.Controls.Add(this.lblStaticCreationDate);
            this.grpStatic5.Controls.Add(this.lblStaticFileCount);
            this.grpStatic5.Controls.Add(this.lblStaticRemainingSectors);
            this.grpStatic5.Controls.Add(this.lblStaticVolumeName);
            this.grpStatic5.Location = new System.Drawing.Point(10, 31);
            this.grpStatic5.Name = "grpStatic5";
            this.grpStatic5.Size = new System.Drawing.Size(410, 64);
            this.grpStatic5.TabIndex = 18;
            this.grpStatic5.TabStop = false;
            // 
            // picStaticRwStatus
            // 
            this.picStaticRwStatus.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.picStaticRwStatus.Image = ((System.Drawing.Image)(resources.GetObject("picStaticRwStatus.Image")));
            this.picStaticRwStatus.Location = new System.Drawing.Point(467, 73);
            this.picStaticRwStatus.Name = "picStaticRwStatus";
            this.picStaticRwStatus.Size = new System.Drawing.Size(15, 15);
            this.picStaticRwStatus.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.picStaticRwStatus.TabIndex = 19;
            this.picStaticRwStatus.TabStop = false;
            // 
            // btnButtonRefresh
            // 
            this.btnButtonRefresh.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonRefresh.Location = new System.Drawing.Point(441, 175);
            this.btnButtonRefresh.Name = "btnButtonRefresh";
            this.btnButtonRefresh.Size = new System.Drawing.Size(75, 24);
            this.btnButtonRefresh.TabIndex = 20;
            this.btnButtonRefresh.Text = "&Refresh";
            this.btnButtonRefresh.Click += new System.EventHandler(this.BtnButtonRefresh_Click);
            // 
            // btnButtonSelectAll
            // 
            this.btnButtonSelectAll.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonSelectAll.Location = new System.Drawing.Point(441, 214);
            this.btnButtonSelectAll.Name = "btnButtonSelectAll";
            this.btnButtonSelectAll.Size = new System.Drawing.Size(75, 24);
            this.btnButtonSelectAll.TabIndex = 21;
            this.btnButtonSelectAll.Text = "&Select All";
            this.btnButtonSelectAll.Click += new System.EventHandler(this.BtnButtonSelectAll_Click);
            // 
            // btnButtonDeselectAll
            // 
            this.btnButtonDeselectAll.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonDeselectAll.Location = new System.Drawing.Point(441, 239);
            this.btnButtonDeselectAll.Name = "btnButtonDeselectAll";
            this.btnButtonDeselectAll.Size = new System.Drawing.Size(75, 24);
            this.btnButtonDeselectAll.TabIndex = 22;
            this.btnButtonDeselectAll.Text = "DeSelect &All";
            this.btnButtonDeselectAll.Click += new System.EventHandler(this.BtnButtonDeselectAll_Click);
            // 
            // lstviewListPartitions
            // 
            this.lstviewListPartitions.Alignment = System.Windows.Forms.ListViewAlignment.Left;
            this.lstviewListPartitions.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.lstviewListPartitions.HideSelection = false;
            this.lstviewListPartitions.Location = new System.Drawing.Point(10, 102);
            this.lstviewListPartitions.MultiSelect = false;
            this.lstviewListPartitions.Name = "lstviewListPartitions";
            this.lstviewListPartitions.Size = new System.Drawing.Size(410, 125);
            this.lstviewListPartitions.TabIndex = 23;
            this.lstviewListPartitions.UseCompatibleStateImageBehavior = false;
            this.lstviewListPartitions.View = System.Windows.Forms.View.Details;
            this.lstviewListPartitions.Visible = false;
            // 
            // treeViewFiles
            // 
            this.treeViewFiles.AllowDrop = true;
            this.treeViewFiles.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.treeViewFiles.FullRowSelect = true;
            this.treeViewFiles.HideSelection = false;
            this.treeViewFiles.Location = new System.Drawing.Point(10, 102);
            this.treeViewFiles.Name = "treeViewFiles";
            this.treeViewFiles.Size = new System.Drawing.Size(367, 362);
            this.treeViewFiles.TabIndex = 24;
            this.treeViewFiles.BeforeCollapse += new System.Windows.Forms.TreeViewCancelEventHandler(this.treeViewFiles_BeforeCollapse);
            this.treeViewFiles.AfterSelect += new System.Windows.Forms.TreeViewEventHandler(this.treeViewFiles_AfterSelect);
            this.treeViewFiles.NodeMouseClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.treeViewFiles_NodeMouseClick);
            this.treeViewFiles.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.treeViewFiles_NodeMouseDoubleClick);
            this.treeViewFiles.DragDrop += new System.Windows.Forms.DragEventHandler(this.treeViewFiles_DragDrop);
            this.treeViewFiles.MouseDoubleClick += new System.Windows.Forms.MouseEventHandler(this.treeViewFiles_MouseDoubleClick);
            // 
            // menuStripMain
            // 
            this.menuStripMain.ImageScalingSize = new System.Drawing.Size(24, 24);
            this.menuStripMain.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItemFile,
            this.toolStripMenuItemEdit,
            this.toolStripMenuItemTools,
            this.toolStripMenuItemImageFile});
            this.menuStripMain.Location = new System.Drawing.Point(0, 0);
            this.menuStripMain.Name = "menuStripMain";
            this.menuStripMain.Size = new System.Drawing.Size(534, 24);
            this.menuStripMain.TabIndex = 25;
            this.menuStripMain.Text = "menuStrip1";
            this.menuStripMain.MenuActivate += new System.EventHandler(this.menuStrip1_MenuActivate);
            // 
            // toolStripMenuItemFile
            // 
            this.toolStripMenuItemFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItemFileOpen,
            this.recentFilesToolStripMenuItem,
            this.toolStripMenuItemFileNew,
            this.toolStripSeparator1,
            this.toolStripMenuItemFileClose,
            this.toolStripSeparator4,
            this.toolStripMenuItemFileRefresh,
            this.toolStripSeparator3,
            this.toolStripMenuItemFileExit});
            this.toolStripMenuItemFile.Name = "toolStripMenuItemFile";
            this.toolStripMenuItemFile.Size = new System.Drawing.Size(37, 20);
            this.toolStripMenuItemFile.Text = "&File";
            // 
            // toolStripMenuItemFileOpen
            // 
            this.toolStripMenuItemFileOpen.Name = "toolStripMenuItemFileOpen";
            this.toolStripMenuItemFileOpen.Size = new System.Drawing.Size(136, 22);
            this.toolStripMenuItemFileOpen.Text = "&Open";
            this.toolStripMenuItemFileOpen.Click += new System.EventHandler(this.toolStripMenuItemFileOpen_Click);
            // 
            // recentFilesToolStripMenuItem
            // 
            this.recentFilesToolStripMenuItem.Name = "recentFilesToolStripMenuItem";
            this.recentFilesToolStripMenuItem.Size = new System.Drawing.Size(136, 22);
            this.recentFilesToolStripMenuItem.Text = "Recent Files";
            this.recentFilesToolStripMenuItem.Click += new System.EventHandler(this.recentFilesToolStripMenuItem_Click);
            // 
            // toolStripMenuItemFileNew
            // 
            this.toolStripMenuItemFileNew.Name = "toolStripMenuItemFileNew";
            this.toolStripMenuItemFileNew.Size = new System.Drawing.Size(136, 22);
            this.toolStripMenuItemFileNew.Text = "&New";
            this.toolStripMenuItemFileNew.Click += new System.EventHandler(this.toolStripMenuItemFileNew_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(133, 6);
            // 
            // toolStripMenuItemFileClose
            // 
            this.toolStripMenuItemFileClose.Name = "toolStripMenuItemFileClose";
            this.toolStripMenuItemFileClose.Size = new System.Drawing.Size(136, 22);
            this.toolStripMenuItemFileClose.Text = "&Close";
            this.toolStripMenuItemFileClose.Click += new System.EventHandler(this.toolStripMenuItemFileClose_Click);
            // 
            // toolStripSeparator4
            // 
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new System.Drawing.Size(133, 6);
            // 
            // toolStripMenuItemFileRefresh
            // 
            this.toolStripMenuItemFileRefresh.Name = "toolStripMenuItemFileRefresh";
            this.toolStripMenuItemFileRefresh.Size = new System.Drawing.Size(136, 22);
            this.toolStripMenuItemFileRefresh.Text = "&Refresh";
            this.toolStripMenuItemFileRefresh.Click += new System.EventHandler(this.toolStripMenuItemFileRefresh_Click);
            // 
            // toolStripSeparator3
            // 
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new System.Drawing.Size(133, 6);
            // 
            // toolStripMenuItemFileExit
            // 
            this.toolStripMenuItemFileExit.Name = "toolStripMenuItemFileExit";
            this.toolStripMenuItemFileExit.Size = new System.Drawing.Size(136, 22);
            this.toolStripMenuItemFileExit.Text = "E&xit";
            this.toolStripMenuItemFileExit.Click += new System.EventHandler(this.toolStripMenuItemFileExit_Click);
            // 
            // toolStripMenuItemEdit
            // 
            this.toolStripMenuItemEdit.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItemEditSelectAll,
            this.toolStripMenuItemEditDeselectAll});
            this.toolStripMenuItemEdit.Name = "toolStripMenuItemEdit";
            this.toolStripMenuItemEdit.Size = new System.Drawing.Size(39, 20);
            this.toolStripMenuItemEdit.Text = "&Edit";
            // 
            // toolStripMenuItemEditSelectAll
            // 
            this.toolStripMenuItemEditSelectAll.Name = "toolStripMenuItemEditSelectAll";
            this.toolStripMenuItemEditSelectAll.Size = new System.Drawing.Size(135, 22);
            this.toolStripMenuItemEditSelectAll.Text = "&Select All";
            this.toolStripMenuItemEditSelectAll.Click += new System.EventHandler(this.toolStripMenuItemEditSelectAll_Click);
            // 
            // toolStripMenuItemEditDeselectAll
            // 
            this.toolStripMenuItemEditDeselectAll.Name = "toolStripMenuItemEditDeselectAll";
            this.toolStripMenuItemEditDeselectAll.Size = new System.Drawing.Size(135, 22);
            this.toolStripMenuItemEditDeselectAll.Text = "&Deselect All";
            this.toolStripMenuItemEditDeselectAll.Click += new System.EventHandler(this.toolStripMenuItemEditDeselectAll_Click);
            // 
            // toolStripMenuItemTools
            // 
            this.toolStripMenuItemTools.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItemToolsEditor,
            this.toolStripMenuItemToolsOptions,
            this.convertDSKToIMAToolStripMenuItem,
            this.toolStripSeparator6,
            this.verifyImageIntegrityToolStripMenuItem});
            this.toolStripMenuItemTools.Name = "toolStripMenuItemTools";
            this.toolStripMenuItemTools.Size = new System.Drawing.Size(46, 20);
            this.toolStripMenuItemTools.Text = "&Tools";
            // 
            // toolStripMenuItemToolsEditor
            // 
            this.toolStripMenuItemToolsEditor.Name = "toolStripMenuItemToolsEditor";
            this.toolStripMenuItemToolsEditor.Size = new System.Drawing.Size(186, 22);
            this.toolStripMenuItemToolsEditor.Text = "&Editor";
            this.toolStripMenuItemToolsEditor.Click += new System.EventHandler(this.toolStripMenuItemToolsEditor_Click);
            // 
            // toolStripMenuItemToolsOptions
            // 
            this.toolStripMenuItemToolsOptions.Name = "toolStripMenuItemToolsOptions";
            this.toolStripMenuItemToolsOptions.Size = new System.Drawing.Size(186, 22);
            this.toolStripMenuItemToolsOptions.Text = "&Options";
            this.toolStripMenuItemToolsOptions.Click += new System.EventHandler(this.toolStripMenuItemToolsOptions_Click);
            // 
            // convertDSKToIMAToolStripMenuItem
            // 
            this.convertDSKToIMAToolStripMenuItem.Name = "convertDSKToIMAToolStripMenuItem";
            this.convertDSKToIMAToolStripMenuItem.Size = new System.Drawing.Size(186, 22);
            this.convertDSKToIMAToolStripMenuItem.Text = "&Convert .DSK to .IMA";
            this.convertDSKToIMAToolStripMenuItem.ToolTipText = "Convert a FLEX .DSK image to a FLEX .IMA image by removing extra sectors from tra" +
    "ck 0 side 0 if required.";
            this.convertDSKToIMAToolStripMenuItem.Click += new System.EventHandler(this.convertDSKToIMAToolStripMenuItem_Click);
            // 
            // toolStripMenuItemImageFile
            // 
            this.toolStripMenuItemImageFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toolStripMenuItemImageFileImport,
            this.toolStripMenuItemImageFileExport,
            this.toolStripSeparator5,
            this.toolStripMenuItemImageFileImportDirectory,
            this.toolStripMenuItemImageFileCreateDirectory,
            this.toolStripSeparator2,
            this.toolStripMenuItemImageFileDelete});
            this.toolStripMenuItemImageFile.Name = "toolStripMenuItemImageFile";
            this.toolStripMenuItemImageFile.Size = new System.Drawing.Size(73, 20);
            this.toolStripMenuItemImageFile.Text = "&Image File";
            // 
            // toolStripMenuItemImageFileImport
            // 
            this.toolStripMenuItemImageFileImport.Name = "toolStripMenuItemImageFileImport";
            this.toolStripMenuItemImageFileImport.Size = new System.Drawing.Size(161, 22);
            this.toolStripMenuItemImageFileImport.Text = "&Import";
            this.toolStripMenuItemImageFileImport.Click += new System.EventHandler(this.toolStripMenuItemImageFileImport_Click);
            // 
            // toolStripMenuItemImageFileExport
            // 
            this.toolStripMenuItemImageFileExport.Name = "toolStripMenuItemImageFileExport";
            this.toolStripMenuItemImageFileExport.Size = new System.Drawing.Size(161, 22);
            this.toolStripMenuItemImageFileExport.Text = "&Export";
            this.toolStripMenuItemImageFileExport.Click += new System.EventHandler(this.toolStripMenuItemImageFileExport_Click);
            // 
            // toolStripSeparator5
            // 
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new System.Drawing.Size(158, 6);
            // 
            // toolStripMenuItemImageFileImportDirectory
            // 
            this.toolStripMenuItemImageFileImportDirectory.Name = "toolStripMenuItemImageFileImportDirectory";
            this.toolStripMenuItemImageFileImportDirectory.Size = new System.Drawing.Size(161, 22);
            this.toolStripMenuItemImageFileImportDirectory.Text = "I&mport Directory";
            this.toolStripMenuItemImageFileImportDirectory.Click += new System.EventHandler(this.toolStripMenuItemImageFileImportDirectory_Click);
            // 
            // toolStripMenuItemImageFileCreateDirectory
            // 
            this.toolStripMenuItemImageFileCreateDirectory.Name = "toolStripMenuItemImageFileCreateDirectory";
            this.toolStripMenuItemImageFileCreateDirectory.Size = new System.Drawing.Size(161, 22);
            this.toolStripMenuItemImageFileCreateDirectory.Text = "&Create Directory";
            this.toolStripMenuItemImageFileCreateDirectory.Click += new System.EventHandler(this.toolStripMenuItemImageFileCreateDirectory_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(158, 6);
            // 
            // toolStripMenuItemImageFileDelete
            // 
            this.toolStripMenuItemImageFileDelete.Name = "toolStripMenuItemImageFileDelete";
            this.toolStripMenuItemImageFileDelete.Size = new System.Drawing.Size(161, 22);
            this.toolStripMenuItemImageFileDelete.Text = "&Delete";
            this.toolStripMenuItemImageFileDelete.Click += new System.EventHandler(this.toolStripMenuItemImageFileDelete_Click);
            // 
            // btnButtonNewDirectory
            // 
            this.btnButtonNewDirectory.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonNewDirectory.Location = new System.Drawing.Point(441, 375);
            this.btnButtonNewDirectory.Name = "btnButtonNewDirectory";
            this.btnButtonNewDirectory.Size = new System.Drawing.Size(75, 23);
            this.btnButtonNewDirectory.TabIndex = 26;
            this.btnButtonNewDirectory.Text = "New Dir";
            this.btnButtonNewDirectory.UseVisualStyleBackColor = true;
            this.btnButtonNewDirectory.Click += new System.EventHandler(this.BtnButtonNewDirectory_Click);
            // 
            // labelFileFormat
            // 
            this.labelFileFormat.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.labelFileFormat.AutoSize = true;
            this.labelFileFormat.Location = new System.Drawing.Point(441, 503);
            this.labelFileFormat.Name = "labelFileFormat";
            this.labelFileFormat.Size = new System.Drawing.Size(79, 13);
            this.labelFileFormat.TabIndex = 27;
            this.labelFileFormat.Text = "                        ";
            // 
            // lstViewPartitions
            // 
            this.lstViewPartitions.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lstViewPartitions.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeaderPartitionName,
            this.columnHeaderName});
            this.lstViewPartitions.FullRowSelect = true;
            this.lstViewPartitions.HideSelection = false;
            this.lstViewPartitions.Location = new System.Drawing.Point(10, 179);
            this.lstViewPartitions.Name = "lstViewPartitions";
            this.lstViewPartitions.Size = new System.Drawing.Size(415, 97);
            this.lstViewPartitions.TabIndex = 28;
            this.lstViewPartitions.UseCompatibleStateImageBehavior = false;
            this.lstViewPartitions.View = System.Windows.Forms.View.Details;
            this.lstViewPartitions.Visible = false;
            this.lstViewPartitions.ItemSelectionChanged += new System.Windows.Forms.ListViewItemSelectionChangedEventHandler(this.lstViewPartitions_ItemSelectionChanged);
            // 
            // columnHeaderPartitionName
            // 
            this.columnHeaderPartitionName.Text = "Partition Name";
            this.columnHeaderPartitionName.Width = 178;
            // 
            // columnHeaderName
            // 
            this.columnHeaderName.Text = "Name";
            this.columnHeaderName.Width = 80;
            // 
            // btnButtonImportDir
            // 
            this.btnButtonImportDir.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnButtonImportDir.Location = new System.Drawing.Point(441, 349);
            this.btnButtonImportDir.Name = "btnButtonImportDir";
            this.btnButtonImportDir.Size = new System.Drawing.Size(75, 23);
            this.btnButtonImportDir.TabIndex = 29;
            this.btnButtonImportDir.Text = "Import Dir";
            this.btnButtonImportDir.UseVisualStyleBackColor = true;
            this.btnButtonImportDir.Click += new System.EventHandler(this.btnButtonImportDirectory_Click);
            // 
            // folderBrowserDialogImportDirectory
            // 
            this.folderBrowserDialogImportDirectory.RootFolder = System.Environment.SpecialFolder.UserProfile;
            // 
            // btnButtonBack
            // 
            this.btnButtonBack.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.btnButtonBack.Location = new System.Drawing.Point(348, 492);
            this.btnButtonBack.Name = "btnButtonBack";
            this.btnButtonBack.Size = new System.Drawing.Size(75, 23);
            this.btnButtonBack.TabIndex = 30;
            this.btnButtonBack.Text = "Back";
            this.btnButtonBack.UseVisualStyleBackColor = true;
            this.btnButtonBack.Visible = false;
            this.btnButtonBack.Click += new System.EventHandler(this.btnButtonBack_Click);
            // 
            // textBoxListViewCurrentPath
            // 
            this.textBoxListViewCurrentPath.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.textBoxListViewCurrentPath.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.textBoxListViewCurrentPath.Location = new System.Drawing.Point(12, 493);
            this.textBoxListViewCurrentPath.Name = "textBoxListViewCurrentPath";
            this.textBoxListViewCurrentPath.ReadOnly = true;
            this.textBoxListViewCurrentPath.Size = new System.Drawing.Size(325, 13);
            this.textBoxListViewCurrentPath.TabIndex = 31;
            this.textBoxListViewCurrentPath.Visible = false;
            // 
            // toolStripSeparator6
            // 
            this.toolStripSeparator6.Name = "toolStripSeparator6";
            this.toolStripSeparator6.Size = new System.Drawing.Size(183, 6);
            // 
            // verifyImageIntegrityToolStripMenuItem
            // 
            this.verifyImageIntegrityToolStripMenuItem.Enabled = false;
            this.verifyImageIntegrityToolStripMenuItem.Name = "verifyImageIntegrityToolStripMenuItem";
            this.verifyImageIntegrityToolStripMenuItem.Size = new System.Drawing.Size(186, 22);
            this.verifyImageIntegrityToolStripMenuItem.Text = "&Verify Image Integrity";
            this.verifyImageIntegrityToolStripMenuItem.Click += new System.EventHandler(this.verifyImageIntegrityToolStripMenuItem_Click);
            // 
            // frmFloppymaintDialog
            // 
            this.AcceptButton = this.btnButtonChangeDisk;
            this.ClientSize = new System.Drawing.Size(534, 532);
            this.Controls.Add(this.textBoxListViewCurrentPath);
            this.Controls.Add(this.btnButtonBack);
            this.Controls.Add(this.btnButtonImportDir);
            this.Controls.Add(this.lstViewPartitions);
            this.Controls.Add(this.labelFileFormat);
            this.Controls.Add(this.btnButtonNewDirectory);
            this.Controls.Add(this.treeViewFiles);
            this.Controls.Add(this.btnButtonChangeDisk);
            this.Controls.Add(this.btnButtonCreate);
            this.Controls.Add(this.btnButtonDelete);
            this.Controls.Add(this.btnButtonDeselectAll);
            this.Controls.Add(this.btnButtonEditor);
            this.Controls.Add(this.btnButtonExport);
            this.Controls.Add(this.btnButtonImport);
            this.Controls.Add(this.btnButtonOptions);
            this.Controls.Add(this.btnButtonRefresh);
            this.Controls.Add(this.btnButtonSelectAll);
            this.Controls.Add(this.btnButtonClose);
            this.Controls.Add(this.lstviewListFiles);
            this.Controls.Add(this.lstviewListPartitions);
            this.Controls.Add(this.picStaticRwStatus);
            this.Controls.Add(this.grpStatic5);
            this.Controls.Add(this.menuStripMain);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MainMenuStrip = this.menuStripMain;
            this.MaximizeBox = false;
            this.Name = "frmFloppymaintDialog";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FloppyMaintenance Version 4.0.0";
            this.Load += new System.EventHandler(this.FrmFloppymaintDialog_Load);
            this.contextMenuStripListFiles.ResumeLayout(false);
            this.grpStatic5.ResumeLayout(false);
            this.grpStatic5.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picStaticRwStatus)).EndInit();
            this.menuStripMain.ResumeLayout(false);
            this.menuStripMain.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }
        #endregion

        private TreeView treeViewFiles;
        private MenuStrip menuStripMain;
        private ToolStripMenuItem toolStripMenuItemFile;
        private ToolStripMenuItem toolStripMenuItemFileOpen;
        private ToolStripMenuItem toolStripMenuItemFileNew;
        private ToolStripSeparator toolStripSeparator1;
        private ToolStripMenuItem toolStripMenuItemFileRefresh;
        private ToolStripMenuItem toolStripMenuItemEdit;
        private ToolStripMenuItem toolStripMenuItemEditSelectAll;
        private ToolStripMenuItem toolStripMenuItemEditDeselectAll;
        private ToolStripMenuItem toolStripMenuItemTools;
        private ToolStripMenuItem toolStripMenuItemToolsEditor;
        private ToolStripMenuItem toolStripMenuItemToolsOptions;
        private ToolStripMenuItem toolStripMenuItemImageFile;
        private ToolStripMenuItem toolStripMenuItemImageFileImport;
        private ToolStripMenuItem toolStripMenuItemImageFileExport;
        private ToolStripMenuItem toolStripMenuItemImageFileCreateDirectory;
        private ToolStripSeparator toolStripSeparator2;
        private ToolStripMenuItem toolStripMenuItemImageFileDelete;
        private Button btnButtonNewDirectory;
        private ToolStripSeparator toolStripSeparator3;
        private ToolStripMenuItem toolStripMenuItemFileExit;
        private ToolStripMenuItem toolStripMenuItemFileClose;
        private ToolStripSeparator toolStripSeparator4;
        private ToolStripSeparator toolStripSeparator5;
        private Label labelFileFormat;
        private ListView lstViewPartitions;
        private ColumnHeader columnHeaderPartitionName;
        private ColumnHeader columnHeaderName;
        private ToolStripMenuItem recentFilesToolStripMenuItem;
        private Button btnButtonImportDir;
        private ToolStripMenuItem toolStripMenuItemImageFileImportDirectory;
        private FolderBrowserDialog folderBrowserDialogImportDirectory;
        private Button btnButtonBack;
        private TextBox textBoxListViewCurrentPath;
        private ContextMenuStrip contextMenuStripListFiles;
        private ToolStripMenuItem findToolStripMenuItem;
        private IContainer components;
        private ToolStripMenuItem convertDSKToIMAToolStripMenuItem;
        private ToolStripSeparator toolStripSeparator6;
        private ToolStripMenuItem verifyImageIntegrityToolStripMenuItem;
    }
}
