//This code has been automatically generated by DudeLabs, LLC RCConverter
using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

namespace FloppyMaintenance
{
	/// <summary>
	/// Summary description for frmProgress.
	/// </summary>

	partial class frmProgress : System.Windows.Forms.Form
		{
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;
        private System.Windows.Forms.Button btnIdcancel;
        private System.Windows.Forms.ProgressBar progressBar1;
        private System.Windows.Forms.Label lblIdcProgdlgPercent;





		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if (components != null) 
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

					#region DudeLabs LLC RCConverter generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.btnIdcancel = new System.Windows.Forms.Button();
            this.progressBar1 = new System.Windows.Forms.ProgressBar();
            this.lblIdcProgdlgPercent = new System.Windows.Forms.Label();
            this.labelMessage = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // btnIdcancel
            // 
            this.btnIdcancel.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.btnIdcancel.Location = new System.Drawing.Point(96, 130);
            this.btnIdcancel.Name = "btnIdcancel";
            this.btnIdcancel.Size = new System.Drawing.Size(75, 24);
            this.btnIdcancel.TabIndex = 1;
            this.btnIdcancel.Text = "Cancel";
            this.btnIdcancel.Click += new System.EventHandler(this.buttonCancel_Click);
            // 
            // progressBar1
            // 
            this.progressBar1.Location = new System.Drawing.Point(22, 29);
            this.progressBar1.Name = "progressBar1";
            this.progressBar1.Size = new System.Drawing.Size(231, 22);
            this.progressBar1.TabIndex = 2;
            this.progressBar1.TabStop = false;
            this.progressBar1.Value = 50;
            // 
            // lblIdcProgdlgPercent
            // 
            this.lblIdcProgdlgPercent.AutoSize = true;
            this.lblIdcProgdlgPercent.Location = new System.Drawing.Point(124, 11);
            this.lblIdcProgdlgPercent.Name = "lblIdcProgdlgPercent";
            this.lblIdcProgdlgPercent.Size = new System.Drawing.Size(27, 13);
            this.lblIdcProgdlgPercent.TabIndex = 3;
            this.lblIdcProgdlgPercent.Text = " 0 %";
            this.lblIdcProgdlgPercent.Visible = false;
            // 
            // labelMessage
            // 
            this.labelMessage.AutoSize = true;
            this.labelMessage.Location = new System.Drawing.Point(19, 70);
            this.labelMessage.MinimumSize = new System.Drawing.Size(35, 13);
            this.labelMessage.Name = "labelMessage";
            this.labelMessage.Size = new System.Drawing.Size(35, 13);
            this.labelMessage.TabIndex = 4;
            // 
            // frmProgress
            // 
            this.AcceptButton = this.btnIdcancel;
            this.ClientSize = new System.Drawing.Size(287, 166);
            this.Controls.Add(this.labelMessage);
            this.Controls.Add(this.btnIdcancel);
            this.Controls.Add(this.lblIdcProgdlgPercent);
            this.Controls.Add(this.progressBar1);
            this.Font = new System.Drawing.Font("Microsoft Sans Serif", 8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmProgress";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = " ";
            this.ResumeLayout(false);
            this.PerformLayout();

        } 
		#endregion

        private Label labelMessage;

	}
}
