
//This code has been automatically generated by DudeLabs LLC RCConverter
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Text;
using System.Windows.Forms;

namespace FloppyMaintenance
{
	/// <summary>
	/// Summary description for frmProgress.
	/// </summary>
	public partial class frmProgress : System.Windows.Forms.Form
	{
        int m_nLower;
        public int LowerBound
        {
            get { return m_nLower; }
            set { m_nLower = value; }
        }

        int m_nUpper;
        public int UpperBound
        {
            get { return m_nUpper; }
            set { m_nUpper = value; }
        }

        int m_nStep;
        public int StepValue
        {
            get { return m_nStep; }
            set { m_nStep = value; }
        }

        public string Message
        {
            set { labelMessage.Text = value; }
        }
 
        public int ProgressValue
        {
            set { progressBar1.Value = value; }
        }

        public frmProgress()
		{
            this.CenterToParent();
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

            m_nLower            = 0;
            m_nUpper            = 100;
            m_nStep             = 10;
		}

        public void SetRange(int lowerbound, int upperbound)
        {
            LowerBound = lowerbound;
            UpperBound = upperbound;
        }

        public void StepIt ()
        {
        }

        public event EventHandler<EventArgs> Canceled;

        private void buttonCancel_Click(object sender, EventArgs e)
        {
            // Create a copy of the event to work with

            EventHandler<EventArgs> ea = Canceled;
            
            // If there are no subscribers, ea will be null so we need to check to avoid a NullReferenceException.

            if (ea != null)
                ea(this, e);
        }
	}
}
